packages:
  - packages/*
  - s2-site

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - core-js-pure
  - electron
  - esbuild
  - fsevents
  - protobufjs
  - vue-demi

onlyBuiltDependencies:
  - canvas
