name: '🙏 Feature request'
description: I have a suggestion (and may want to implement it) / 我有一个建议（或者想参与贡献）
title: '🙏'
labels: ['🙏feature request']
body:
  - type: markdown
    attributes:
      value: |
        如果你遇到了问题，或者对 [Issues](https://github.com/antvis/S2/issues) 和 [Discussions](https://github.com/antvis/S2/discussions) 列表的问题感兴趣，**可以直接认领并尝试修复**，帮助 S2 变得更好，期待在 [贡献者列表](https://github.com/antvis/S2/graphs/contributors) 里看见你的头像。

        S2 非常需要你的共建，请阅读 [贡献指南](https://s2.antv.antgroup.com/manual/contribution) 后提交 PR.

  - type: textarea
    id: description
    attributes:
      label: Describe the feature / 功能描述
      placeholder: |
        What problem does this feature solve? Where are the existing features not enough?
        这个功能能解决什么问题？ 现有功能不满足的点在哪？

    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Design the API / API 设计
      placeholder: |
        If you need to add an API, how do you want to design it?
        如果需要新增 API, 你希望怎么设计？

        | name | type | default | description |
        | ---- | ---- | ------- | ----------- |
        | -    | -    | -       | -           |

      value: |
        | name | type | default | description |
        | ---- | ---- | ------- | ----------- |
        | -    | -    | -       | -           |

    validations:
      required: true

  - type: dropdown
    attributes:
      label: Are you willing to contribute? / 是否愿意参与贡献？
      options:
        - Please select / 请选择
        - ✅ Yes / 是
        - ❌ No / 否
    validations:
      required: true
