export const VALUE_RANGES_KEY = 'valueRanges';
export const DEFAULT_VALUE_RANGES = {};
export const INDICATE_CONDITION_SYMBOL = Symbol.for('indicate condition'); // used for distinguish whether the condition is generated by indicateConditionValues
