name: 🔔 Community Notify

on:
  issues:
    types: [opened]
  discussion:
    types: [created]
  pull_request_target:
    types: [opened]

permissions: {}

jobs:
  issue-created:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: DingTalk issue notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TALK_ACCESS_TOKEN }}
          ignoreError: true
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": ${{ toJSON(format('📢 新 Issue #{0}: {1}', github.event.issue.number, github.event.issue.title)) }},
                "text": ${{ toJSON(format('用户: {0}', github.event.issue.user.login)) }},
                "messageUrl": ${{ toJSON(github.event.issue.html_url) }},
                "picUrl": "https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*1PTTQLk3j5AAAAAAAAAAAAAADmJ7AQ/original"
              }
            }

  discussion-created:
    if: github.event_name == 'discussion'
    runs-on: ubuntu-latest
    steps:
      - name: DingTalk discussion notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TALK_ACCESS_TOKEN }}
          ignoreError: true
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": ${{ toJSON(format('📢 新 Discussion: {0}', github.event.discussion.title)) }},
                "text": ${{ toJSON(format('用户: {0}', github.event.discussion.user.login)) }},
                "messageUrl": ${{ toJSON(github.event.discussion.html_url) }},
                "picUrl": "https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*1PTTQLk3j5AAAAAAAAAAAAAADmJ7AQ/original"
              }
            }

  pull-request-opened:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - name: DingTalk pull request notify
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TALK_ACCESS_TOKEN }}
          ignoreError: true
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": ${{ toJSON(format('📢 新 PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title)) }},
                "text": ${{ toJSON(format('用户: {0}', github.event.pull_request.user.login)) }},
                "messageUrl": ${{ toJSON(github.event.pull_request.html_url) }},
                "picUrl": "https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*1PTTQLk3j5AAAAAAAAAAAAAADmJ7AQ/original"
              }
            }
