name: Issue Check Inactive

on:
  schedule:
    - cron: "0 0 */15 * *"


jobs:
  issue-check-inactive:
    runs-on: ubuntu-latest
    steps:
      - name: Check Inactive
        uses: actions-cool/issues-helper@main
        with:
          actions: 'check-inactive'
          inactive-label: '💤 inactive'
          inactive-day: 30
