name: 👨‍🔬 lint

on: [pull_request]

concurrency:
  group: ${{github.workflow}}-${{github.event_name}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      # Python 3.11 和 node-gyp 有兼容问题, 导致无法安装依赖
      # https://github.com/slint-ui/slint/commit/a9c48e33502fdebc36c5aa2f4f516c2218424679#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133dd
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm bootstrap:ci

      - name: Lint scripts, type, style and docs
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Bundle size limit
        run: pnpm build:size-limit
        env:
          CI: true
