name: 🔊 PR Ding Talk Notify

on:
  pull_request_target:
    types: [opened]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Ding Talk PR Notify
        uses: lijinke666/ding-talk-pr-notify@main
        with:
          ding_talk_token: ${{ secrets.DING_TALK_ACCESS_TOKEN }}
          at_all: false
