name: PR Opened

on:
  pull_request_target:
    types: [opened]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Auto tips
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            你好 @${{ github.event.pull_request.user.login }}，非常感谢你的贡献.
            为了让代码更健壮, 请根据 [贡献指南](https://s2.antv.antgroup.com/manual/contribution) 补充相应单元测试 (文档改动或其他特殊场景除外), 如果有 API 改动, 请修改 [相应的文档](https://github.com/antvis/S2/tree/next/s2-site).
            同时请检查 `lint` 和 `test` 相关 CI 是否通过, 如果失败, 请点击 [Details] 按钮查看, 并根据日志修复.

            Hello, @${{ github.event.pull_request.user.login }}, Thanks for your contribution. In order to make the code more robust, please add the corresponding unit tests, and update the [docs](https://github.com/antvis/S2/tree/next/s2-site) if there are API changes.
            At the same time, please check whether the CI related to lint and test passes. If the CI fails, please click [Details] button to check and repair according to the log.
