name: 🚀 After the release is successful

# 自动发布 action 执行完成后再执行 (无论成功失败都会执行)
on:
  workflow_run:
    workflows: ["🚀 Auto Release"]
    branches: [latest] # 只有正式版发布才同步 changelog
    types:
      - completed

jobs:
  sync-site-lock:
    runs-on: ubuntu-latest
    # 自动发布成功后
    if: github.event.workflow_run.conclusion == 'success'
    defaults:
      run:
        working-directory: s2-site

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Git bootstrap
        run: |
          git config --global user.name 'Jinke Li'
          git config --global user.email 'a1231236677287@163.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.HUIYU_GITHUB_TOKEN }}

      - name: Checkout branch
        run: |
          git checkout -b chore-sync
          git fetch --all
          git merge origin/latest --squash

      - name: Push lock
        run: |
          git add .
          git commit -m "chore: 🤖 更新 changelog 文件" -n
          git push origin chore-sync --no-verify -f

      # 使用官方的 github cli 便捷的创建 pr
      - name: Create PR
        run: |
          gh pr create --title "chore: 🤖 更新 changelog 文件" --body "![preview](https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*Eel8Rp5jlAkAAAAAAAAAAAAADmJ7AQ/original) <br/> 🤖 由 [[🚀 After the release is successful](https://github.com/antvis/S2/blob/master/.github/workflows/release-success.yml)] action 自动创建."
        env:
          GITHUB_TOKEN: ${{ secrets.HUIYU_GITHUB_TOKEN }}

      # 失败通知
      - name: 🔊 Create failed notify
        if: ${{ failure() }}
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TALK_ACCESS_TOKEN }}
          ignoreError: true
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": "🚨 同步 CHANGELOG 失败",
                "text": "🔗 请点击链接查看具体原因, 尝试点击右上角 [Re-run all jobs] 重试 🚑",
                "messageUrl": "https://github.com/antvis/S2/actions/workflows/release-success.yml",
                "picUrl": "https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*PRSkSqsE_vYAAAAAAAAAAAAADmJ7AQ/original"
              }
            }
