name: 📦 size limit

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    strategy:
        matrix:
          node-version: [18]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      # https://github.com/ant-design/ant-design/blob/master/.github/workflows/size-limit.yml
      - name: size-limit
        uses: ant-design/size-limit-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build:umd
          skip_step: install
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          PRODUCTION_ONLY: 1
