name: 💯 test (@antv/s2)

on: [pull_request]

concurrency:
  group: ${{github.workflow}}-${{github.event_name}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    # jest-electron 需要 macOS 环境, 但是 免费用户 并发有限制, 容易排队 https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    # runs-on: macos-latest # (目前 macos-latest 对应的是 Big Sur 11, macos-12 对应  Monterey 12)
    # macOS 3-core CPU, 其他 2-core CPU
    runs-on: macos-14
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      # Python 3.11 和 node-gyp 有兼容问题, 导致无法安装依赖
      # https://github.com/slint-ui/slint/commit/a9c48e33502fdebc36c5aa2f4f516c2218424679#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133dd
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm bootstrap:ci

      - name: Test
        run: |
          pnpm --filter @antv/s2 test:ci-coverage
        env:
          DEBUG: jest*
